services:
  mysqldb:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  app:
    depends_on:
      - mysqldb
    image: azurebook/todoapp-app
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    restart: always
